name: build_gromacs

on:
  # Triggers on push and pull-request in branch 'manuel'
  push:
    branches: [ manuel ]
  pull_request:
    branches: [ manuel ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    runs-on: ubuntu-latest
    steps:
      # Create a build directory
      - run: mkdir build
      # Change to build directory
      - run: cd build
      # Run cmake
      - run: cmake .. -DGMX_BUILD_OWN_FFTW=ON -DREGRESSIONTEST_DOWNLOAD=ON
      # Install
      - run: make
      - run: make install